name: CI/CD Security Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run ESLint for code analysis
    - name: Run ESLint
      run: npx eslint index.js || exit 1

    # Step 5: Use CodeQL for security scanning
    - name: CodeQL Analyze
      uses: github/codeql-action/analyze@v2
      with:
        category: security
